# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
      tasks: ["lintFlossDebug"]
      # , "testDebugUnitTest", "testFlossDebugUnitTest"]
    )
  end

  desc "Build Play bundle"
  lane :buildPlayRelease do
    gradle(
      task: "bundle",
      build_type: "Release",
      flavor: "Play"
    )
  end

  desc "Build Floss APK"
  lane :buildFlossRelease do
    gradle(
        task: "assemble",
        build_type: "Release",
        flavor: "Floss"
    )
  end

  desc "Release a new version to Google Play"
  lane :release do
    # Convert current version to integer
    current_version = ENV["VERSION_CODE"].to_i
    publish_version = google_play_track_version_codes(
      track: "internal"
    ).first

    UI.message("Published: #{publish_version}, Current: #{current_version}")
    if publish_version >= current_version
      UI.important("Version code already published, skipping upload")
      exit(0)
    end

    buildPlayRelease
    supply(
      track: "internal",
      skip_upload_apk: true,
      sync_image_upload: true
    )
  end
end
