name: Create tagged release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version-file: .java-version
          cache: 'gradle'
      # https://developer.android.com/tools/variables
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - run: .github/scripts/encode.sh decode
        env:
          APP_GOOGLE_SERVICES_JSON: ${{ secrets.APP_GOOGLE_SERVICES_JSON }}
          FASTLANE_IAM_KEY_JSON: ${{ secrets.FASTLANE_IAM_KEY_JSON }}
          GRADLE_RELEASE_KEYSTORE: ${{ secrets.GRADLE_RELEASE_KEYSTORE }}
          GRADLE_RELEASE_SIGNING: ${{ secrets.GRADLE_RELEASE_SIGNING }}
      - run: .github/scripts/lint-changelog.sh
      - run: fastlane buildFlossRelease
      - name: Release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
            fail_on_unmatched_files: true
            make_latest: true
            body_path: ${{ env.CHANGELOG_FILE }}
            files: |
                app/build/outputs/apk/floss/release/app-floss-release.apk
